//FOR --> FAZ PARTE DE QAUSE TODAS AS LINGUAGENS DE PROGRAMAÇÃO
const numeros = [100,200,300,400,500,600];


//PRIMEIRA EXPRESSÃO: EXECUTADA UMA SÓ VEZ;
//SEGUNDA EXPRESSÃO: CONDIÇÃO DE EXECUÇÃO DO NOSSO BLOCO FOR;
//TERCEIRA CONDIÇÃO: EXPRESSÃO EXECUTADA SEMPRE AO FINAL DO BLOCO;
for(let indice=0; indice < numeros.length; indice++){
    console.log(numeros[indice])
}

//ITERAÇÃO --> CADA VEZ QUE O CÓDIGO É EXECUTADO